/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysInventario.AL;

import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import sysInventario.Model.Usuario;
import sysInventario.BL.UsuarioBL;

public class LoginForm extends javax.swing.JFrame {

    int x;
    int y;
    int a;
    int b;

    public LoginForm() {

        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icons8_shopping_cart_50px.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Minimizar = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnentrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesion");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minus_35px.png"))); // NOI18N
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizarMousePressed(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 40, 30));

        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cancel_35px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 40, 30));

        User.setForeground(new java.awt.Color(63, 61, 86));
        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_password_35px.png"))); // NOI18N
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 40));

        Password.setForeground(new java.awt.Color(63, 61, 86));
        Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_35px_1.png"))); // NOI18N
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 40));

        txtuser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtuser.setForeground(new java.awt.Color(63, 61, 86));
        txtuser.setText("Nombre de usuario");
        txtuser.setBorder(null);
        txtuser.setOpaque(false);
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
        });
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 340, 40));

        txtpass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtpass.setForeground(new java.awt.Color(63, 61, 86));
        txtpass.setText("Click Password...");
        txtpass.setBorder(null);
        txtpass.setOpaque(false);
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassMousePressed(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 340, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 61, 86));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign in to continue");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, -1));

        jSeparator1.setBackground(new java.awt.Color(63, 61, 86));
        jSeparator1.setForeground(new java.awt.Color(63, 61, 86));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 370, 10));

        jSeparator2.setBackground(new java.awt.Color(63, 61, 86));
        jSeparator2.setForeground(new java.awt.Color(63, 61, 86));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 370, 10));

        btnentrar.setBackground(new java.awt.Color(83, 109, 254));
        btnentrar.setForeground(new java.awt.Color(83, 109, 254));
        btnentrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnentrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnentrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnentrarMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_play_40px.png"))); // NOI18N
        jLabel2.setText("Start");

        javax.swing.GroupLayout btnentrarLayout = new javax.swing.GroupLayout(btnentrar);
        btnentrar.setLayout(btnentrarLayout);
        btnentrarLayout.setHorizontalGroup(
            btnentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnentrarLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        btnentrarLayout.setVerticalGroup(
            btnentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 390, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_twitter_circled_35px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 50, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_play_button_35px.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 50, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_facebook_circled_35px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 50, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(63, 61, 86));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WELCOME BACK,");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 350, -1));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.PNG"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 660));

        setSize(new java.awt.Dimension(449, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMousePressed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMousePressed

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        this.setLocation(x1 - x, y1 - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnentrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnentrarMouseEntered
        // TODO add your handling code here:
        btnentrar.setBackground(new Color(63, 61, 86));
    }//GEN-LAST:event_btnentrarMouseEntered

    private void btnentrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnentrarMouseExited
        // TODO add your handling code here
        btnentrar.setBackground(new Color(83, 109, 254));
    }//GEN-LAST:event_btnentrarMouseExited

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
        // TODO add your handling code here:
        String user = "Nombre de usuario";
        if (user.equals(txtuser.getText())) {
            txtuser.setText("");
            jSeparator2.setBackground(new Color(83, 109, 254));
            jSeparator2.setForeground(new Color(83, 109, 254));
            jSeparator1.setBackground(new Color(63, 61, 86));
            jSeparator1.setForeground(new Color(63, 61, 86));
        } else {
            jSeparator2.setBackground(new Color(83, 109, 254));
            jSeparator2.setForeground(new Color(83, 109, 254));
            jSeparator1.setBackground(new Color(63, 61, 86));
            jSeparator1.setForeground(new Color(63, 61, 86));
            //lbl_informcion.setText("");
        }
    }//GEN-LAST:event_txtuserKeyPressed

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        // TODO add your handling code here:
        String user = "Nombre de usuario";
        if (user.equals(txtuser.getText())) {
            txtuser.setText("");
            jSeparator2.setBackground(new Color(83, 109, 254));
            jSeparator2.setForeground(new Color(83, 109, 254));
            jSeparator1.setBackground(new Color(63, 61, 86));
            jSeparator1.setForeground(new Color(63, 61, 86));
        } else {
            jSeparator2.setBackground(new Color(83, 109, 254));
            jSeparator2.setForeground(new Color(83, 109, 254));
            jSeparator1.setBackground(new Color(63, 61, 86));
            jSeparator1.setForeground(new Color(63, 61, 86));
            //lbl_informcion.setText("");
        }
    }//GEN-LAST:event_txtuserMousePressed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        // TODO add your handling code here:
        String pas = "";
        String pass = "Click Password...";
        char con[] = txtpass.getPassword();

        for (int i = 0; i < con.length; i++) {
            pas += con[i];

        }
        if (pass.equals(pas)) {
            txtpass.setText("");
            jSeparator1.setBackground(new Color(83, 109, 254));
            jSeparator1.setForeground(new Color(83, 109, 254));
            jSeparator2.setBackground(new Color(63, 61, 86));
            jSeparator2.setForeground(new Color(63, 61, 86));
        } else {
            jSeparator1.setBackground(new Color(83, 109, 254));
            jSeparator1.setForeground(new Color(83, 109, 254));
            jSeparator2.setBackground(new Color(63, 61, 86));
            jSeparator2.setForeground(new Color(63, 61, 86));

        }
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMousePressed
        // TODO add your handling code here:
        String pas = "";
        String pass = "Click Password...";
        char con[] = txtpass.getPassword();

        for (int i = 0; i < con.length; i++) {
            pas += con[i];

        }
        if (pass.equals(pas)) {
            txtpass.setText("");
            jSeparator1.setBackground(new Color(83, 109, 254));
            jSeparator1.setForeground(new Color(83, 109, 254));
            jSeparator2.setBackground(new Color(63, 61, 86));
            jSeparator2.setForeground(new Color(63, 61, 86));
        } else {
            jSeparator1.setBackground(new Color(83, 109, 254));
            jSeparator1.setForeground(new Color(83, 109, 254));
            jSeparator2.setBackground(new Color(63, 61, 86));
            jSeparator2.setForeground(new Color(63, 61, 86));

        }
    }//GEN-LAST:event_txtpassMousePressed

    private void btnentrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnentrarMousePressed
        // TODO add your handling code here:

        String nombreUsuario, contrasena;

        nombreUsuario = txtuser.getText().trim();
        contrasena = String.valueOf(txtpass.getPassword()).trim();

        if (nombreUsuario.isEmpty() || nombreUsuario.equals("Nombre de usuario")) {

            JOptionPane.showMessageDialog(null, "Campo vacio, completelo!");

        } else if (contrasena.isEmpty() || contrasena.equals("Click Password...")) {
            JOptionPane.showMessageDialog(null, "Campo vacio, completelo!");
        } else {
            Usuario usuario = new Usuario(nombreUsuario);
            boolean valido = UsuarioBL.validarUsuario(usuario, contrasena);

            if (valido) {
                MainForm f = new MainForm();
                f.setUsuarioLogeado(usuario);
                f.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Nombre de usuario incorrecto");
            }
        }

    }//GEN-LAST:event_btnentrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel User;
    private javax.swing.JPanel btnentrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
