/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysInventario.AL;

import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import sysInventario.Model.Usuario;

/**
 *
 * @author Ara-PC
 */
public class MainForm extends javax.swing.JFrame {
    
    private Usuario usuariologeado;
    
    void setUsuarioLogeado(Usuario usuariologeado) {
        this.usuariologeado = usuariologeado;
    }
    
    public MainForm() {
        
        initComponents();
        
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icons8_shopping_cart_50px.png")).getImage());
        
    }
    
    public void setColor(JPanel panel) {
        panel.setBackground(new Color(108, 117, 125));
        
    }
    
    public void resetColor(JPanel panel) {
        panel.setBackground(new Color(63, 61, 86));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabezera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lateral = new javax.swing.JPanel();
        inicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        productos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pedidos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        recepcionPedidos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        stockProductos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usuariosADMIN = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        salirSYSTEM = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Central = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cabezera.setBackground(new java.awt.Color(63, 61, 86));
        cabezera.setPreferredSize(new java.awt.Dimension(1000, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo II.PNG"))); // NOI18N

        lblCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shutdown_25px.png"))); // NOI18N
        lblCerrarSesion.setText("Cerrar Sesión");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMousePressed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_25px.png"))); // NOI18N
        lblUsername.setText("Nombre de usuario");

        javax.swing.GroupLayout cabezeraLayout = new javax.swing.GroupLayout(cabezera);
        cabezera.setLayout(cabezeraLayout);
        cabezeraLayout.setHorizontalGroup(
            cabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cabezeraLayout.setVerticalGroup(
            cabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraLayout.createSequentialGroup()
                .addGroup(cabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cabezeraLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(cabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        lateral.setBackground(new java.awt.Color(63, 61, 86));
        lateral.setPreferredSize(new java.awt.Dimension(250, 540));
        lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio.setBackground(new java.awt.Color(63, 61, 86));
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_dog_house_25px.png"))); // NOI18N
        jLabel3.setText("INICIO");

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lateral.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 40));

        productos.setBackground(new java.awt.Color(63, 61, 86));
        productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productosMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_product_25px.png"))); // NOI18N
        jLabel4.setText("PRODUCTOS");

        javax.swing.GroupLayout productosLayout = new javax.swing.GroupLayout(productos);
        productos.setLayout(productosLayout);
        productosLayout.setHorizontalGroup(
            productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        productosLayout.setVerticalGroup(
            productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lateral.add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, 40));

        pedidos.setBackground(new java.awt.Color(63, 61, 86));
        pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pedidosMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_playlist_25px.png"))); // NOI18N
        jLabel5.setText("PEDIDOS");

        javax.swing.GroupLayout pedidosLayout = new javax.swing.GroupLayout(pedidos);
        pedidos.setLayout(pedidosLayout);
        pedidosLayout.setHorizontalGroup(
            pedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedidosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pedidosLayout.setVerticalGroup(
            pedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lateral.add(pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 40));

        recepcionPedidos.setBackground(new java.awt.Color(63, 61, 86));
        recepcionPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recepcionPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recepcionPedidosMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_deliver_food_25px.png"))); // NOI18N
        jLabel6.setText("RECEPCIÓN DE PEDIDOS");

        javax.swing.GroupLayout recepcionPedidosLayout = new javax.swing.GroupLayout(recepcionPedidos);
        recepcionPedidos.setLayout(recepcionPedidosLayout);
        recepcionPedidosLayout.setHorizontalGroup(
            recepcionPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionPedidosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        recepcionPedidosLayout.setVerticalGroup(
            recepcionPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lateral.add(recepcionPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        stockProductos.setBackground(new java.awt.Color(63, 61, 86));
        stockProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockProductosMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(63, 61, 86));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_out_of_stock_25px.png"))); // NOI18N
        jLabel7.setText("PRODUCTOS CON STOCK BAJOS");

        javax.swing.GroupLayout stockProductosLayout = new javax.swing.GroupLayout(stockProductos);
        stockProductos.setLayout(stockProductosLayout);
        stockProductosLayout.setHorizontalGroup(
            stockProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockProductosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        stockProductosLayout.setVerticalGroup(
            stockProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lateral.add(stockProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONTROL INVENTARIO");
        lateral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 250, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ADMINISTRACIÓN");
        lateral.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, 40));

        usuariosADMIN.setBackground(new java.awt.Color(63, 61, 86));
        usuariosADMIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuariosADMINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuariosADMINMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_team_25px_2.png"))); // NOI18N
        jLabel9.setText("USUARIOS");

        javax.swing.GroupLayout usuariosADMINLayout = new javax.swing.GroupLayout(usuariosADMIN);
        usuariosADMIN.setLayout(usuariosADMINLayout);
        usuariosADMINLayout.setHorizontalGroup(
            usuariosADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosADMINLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        usuariosADMINLayout.setVerticalGroup(
            usuariosADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lateral.add(usuariosADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 250, 40));

        salirSYSTEM.setBackground(new java.awt.Color(63, 61, 86));
        salirSYSTEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirSYSTEMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirSYSTEMMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirSYSTEMMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_exit_25px.png"))); // NOI18N
        jLabel10.setText("SALIR DEL SISTEMA");

        javax.swing.GroupLayout salirSYSTEMLayout = new javax.swing.GroupLayout(salirSYSTEM);
        salirSYSTEM.setLayout(salirSYSTEMLayout);
        salirSYSTEMLayout.setHorizontalGroup(
            salirSYSTEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salirSYSTEMLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        salirSYSTEMLayout.setVerticalGroup(
            salirSYSTEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lateral.add(salirSYSTEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 250, 40));
        lateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 20));
        lateral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 140, 20));

        Central.setBackground(new java.awt.Color(255, 255, 255));
        Central.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Central, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(cabezera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cabezera, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Central, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lateral, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1000, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseEntered
        // TODO add your handling code here:
        setColor(inicio);

    }//GEN-LAST:event_inicioMouseEntered

    private void inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseExited
        // TODO add your handling code here:
        resetColor(inicio);
    }//GEN-LAST:event_inicioMouseExited

    private void productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseEntered
        // TODO add your handling code here:
        setColor(productos);
    }//GEN-LAST:event_productosMouseEntered

    private void productosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseExited
        // TODO add your handling code here:
        resetColor(productos);
    }//GEN-LAST:event_productosMouseExited

    private void pedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidosMouseEntered
        // TODO add your handling code here:
        setColor(pedidos);
    }//GEN-LAST:event_pedidosMouseEntered

    private void pedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidosMouseExited
        // TODO add your handling code here:
        resetColor(pedidos);
    }//GEN-LAST:event_pedidosMouseExited

    private void recepcionPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recepcionPedidosMouseEntered
        // TODO add your handling code here:
        setColor(recepcionPedidos);
    }//GEN-LAST:event_recepcionPedidosMouseEntered

    private void recepcionPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recepcionPedidosMouseExited
        // TODO add your handling code here:
        resetColor(recepcionPedidos);
    }//GEN-LAST:event_recepcionPedidosMouseExited

    private void stockProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockProductosMouseEntered
        // TODO add your handling code here:
        setColor(stockProductos);
    }//GEN-LAST:event_stockProductosMouseEntered

    private void stockProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockProductosMouseExited
        // TODO add your handling code here:
        resetColor(stockProductos);
    }//GEN-LAST:event_stockProductosMouseExited

    private void usuariosADMINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosADMINMouseEntered
        // TODO add your handling code here:
        setColor(usuariosADMIN);
    }//GEN-LAST:event_usuariosADMINMouseEntered

    private void usuariosADMINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosADMINMouseExited
        // TODO add your handling code here:
        resetColor(usuariosADMIN);
    }//GEN-LAST:event_usuariosADMINMouseExited

    private void salirSYSTEMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirSYSTEMMouseEntered
        // TODO add your handling code here:
        setColor(salirSYSTEM);
    }//GEN-LAST:event_salirSYSTEMMouseEntered

    private void salirSYSTEMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirSYSTEMMouseExited
        // TODO add your handling code here:
        resetColor(salirSYSTEM);
    }//GEN-LAST:event_salirSYSTEMMouseExited

    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        // TODO add your handling code here:
        lblCerrarSesion.setForeground(new Color(108, 117, 125));

    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
        // TODO add your handling code here:
        lblCerrarSesion.setForeground(Color.white);

    }//GEN-LAST:event_lblCerrarSesionMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.lblUsername.setText(usuariologeado.getNombreUsuario());
    }//GEN-LAST:event_formWindowOpened

    private void lblCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMousePressed
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCerrarSesionMousePressed

    private void salirSYSTEMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirSYSTEMMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirSYSTEMMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Central;
    private javax.swing.JPanel cabezera;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel lateral;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pedidos;
    private javax.swing.JPanel productos;
    private javax.swing.JPanel recepcionPedidos;
    private javax.swing.JPanel salirSYSTEM;
    private javax.swing.JPanel stockProductos;
    private javax.swing.JPanel usuariosADMIN;
    // End of variables declaration//GEN-END:variables
}
